// ─── Daily Levels ───
// Niveaux quotidiens hardcodés pour le jeu
// Tous les niveaux sont des puzzles stratégiques
// Le cheval commence libre, les obstacles créent des zones à conquérir

export const DAILY_LEVELS = [
  {
    id: 1,
    name: 'Open Field',
    dayNumber: 1,
    wallBudget: 5,
    optimalScore: 12,
    map: [
      '...~~....',
      '...~~....',
      '...~~H...',
      '...~~....',
      '.~~..~~..',
      '.~~..~~..',
      '...~~....',
      '..........',
    ].join('\n'),
  },
  {
    id: 2,
    name: 'Divide & Conquer',
    dayNumber: 2,
    wallBudget: 8,
    optimalScore: 18,
    map: [
      '.......~~~~~.',
      '.......~~~~~.',
      '..H....~~~~~.',
      '.......~~~~~.',
      '.~~~~~.......',
      '.~~~~~...C...',
      '.~~~~~.......',
      '..............',
    ].join('\n'),
  },
  {
    id: 3,
    name: 'Two Chambers',
    dayNumber: 3,
    wallBudget: 10,
    optimalScore: 22,
    map: [
      '~...C.~......~',
      '~.......~.....~',
      '~..H.......G.~',
      '~.......~.....~',
      '~...........~',
      '.................',
    ].join('\n'),
  },
  {
    id: 4,
    name: 'Island Hopping',
    dayNumber: 4,
    wallBudget: 9,
    optimalScore: 20,
    map: [
      '~~~~.....~~~~',
      '~~~~.....~~~~',
      '....H....C...',
      '....~....~...',
      '....~....~...',
      '~~~~~...~~~~~',
      '~~~~~...~~~~~',
      '~~~~~...~~~~~',
      '.............',
    ].join('\n'),
  },
  {
    id: 5,
    name: 'Open Channels',
    dayNumber: 5,
    wallBudget: 11,
    optimalScore: 26,
    map: [
      '...~.....~.~.~...',
      '...~.....~.~.~...',
      '...~H....~.~.~C..',
      '...~.....~.~.~...',
      '...~....G~.~.~...',
      '...~.....~.~.~...',
      '....................',
    ].join('\n'),
  },
  {
    id: 6,
    name: 'Strategic Blocks',
    dayNumber: 6,
    wallBudget: 10,
    optimalScore: 24,
    map: [
      '......~...~...',
      '....~~.~~.~~..',
      '...H.....C....',
      '....~~.~~.~~..',
      '......~...~.G.',
      '................',
      '................',
    ].join('\n'),
  },
  {
    id: 7,
    name: 'Corridor Choice',
    dayNumber: 7,
    wallBudget: 12,
    optimalScore: 28,
    map: [
      '~.~.~.~.~.~',
      '.~.~.~.~.~.',
      '~H~.~.C.~.~',
      '.~.~.~.~.~.',
      '~.~.~.~.~.~',
      '.~.~.G.~.~.',
      '~.~.~.~.~.~',
      '.................~',
    ].join('\n'),
  },
  {
    id: 8,
    name: 'Spread Out',
    dayNumber: 8,
    wallBudget: 10,
    optimalScore: 22,
    map: [
      '...~~...~~...~~',
      '...~~...~~...~~',
      'H.......C......G',
      '...~~...~~...~~',
      '...~~...~~...~~',
      '.................',
      '.................',
    ].join('\n'),
  },
  {
    id: 9,
    name: 'Scattered Zones',
    dayNumber: 9,
    wallBudget: 11,
    optimalScore: 25,
    map: [
      '~~....~~....~~',
      '~~....~~....~~',
      '....H.....C...',
      '~~....~~....~~',
      '~~....~~....~~',
      '.....G........',
      '................',
    ].join('\n'),
  },
  {
    id: 10,
    name: 'Open Maze',
    dayNumber: 10,
    wallBudget: 13,
    optimalScore: 32,
    map: [
      '.~~~...~~~...~~.',
      '.~~~...~~~...~~.',
      '.......H......C.',
      '.~~~...~~~...~~.',
      '.~~~...~~~...~~.',
      '...................G......',
      '.................',
      '.................',
    ].join('\n'),
  },
  {
    id: 11,
    name: 'Free Roaming',
    dayNumber: 11,
    wallBudget: 12,
    optimalScore: 28,
    map: [
      '~.~.~.~.~.~.~.',
      '.~.~.~.~.~.~.~',
      '~H~.~C~.~.~.~.',
      '.~.~.~.~.~.~.~',
      '~.~.~.~.~.~.~.',
      '.~.~.~G~.~.~.~',
      '~.~.~.~.~.~.~.',
      '....................',
    ].join('\n'),
  },
  {
    id: 12,
    name: 'Wide Open Spaces',
    dayNumber: 12,
    wallBudget: 11,
    optimalScore: 26,
    map: [
      '...~~.....~~...',
      '...~~.....~~...',
      'H.......C......',
      '...~~.....~~...',
      '...~~.....~~...',
      '........G......',
      '................',
      '................',
    ].join('\n'),
  },
  {
    id: 13,
    name: 'Strategic Gaps',
    dayNumber: 13,
    wallBudget: 14,
    optimalScore: 34,
    map: [
      '~~~.~~~.~~~.~~~',
      '~~~.~~~.~~~.~~~',
      '...H...C...G...',
      '~~~.~~~.~~~.~~~',
      '~~~.~~~.~~~.~~~',
      '..................',
      '..................',
      '..................',
    ].join('\n'),
  },
  {
    id: 14,
    name: 'Balanced Design',
    dayNumber: 14,
    wallBudget: 12,
    optimalScore: 30,
    map: [
      '...~.....~....~',
      '...~.....~....~',
      'H......C......G',
      '...~.....~....~',
      '...~.....~....~',
      '.................~',
      '.................~',
    ].join('\n'),
  },
  {
    id: 15,
    name: 'Ultimate Challenge',
    dayNumber: 15,
    wallBudget: 15,
    optimalScore: 40,
    map: [
      '~.~.~.~.~.~.~.~.',
      '.~.~.~.~.~.~.~.~',
      '~H~.~C~.~G~.~.~.',
      '.~.~.~.~.~.~.~.~',
      '~.~.~.~.~.~.~.~.',
      '.~.~.~.~.~.~.~.~',
      '~.~.~.~.~.~.~.~.',
      '..........................',
    ].join('\n'),
  },
];
